### ISSUE TITLE
Missing Entities

### ISSUE THREAD

**Issue by jasonyates** [tube0013/Smartcar-HA#5]
I can see from the logs in Smartcar that the integration is successfully pulling various enpoints such as Fuel Tank, Odometer, Lock Status, Tyre Pressure however I only have the Odometer entity created in HA.

**Comment by tube0013** [comment]
Hi, can you enable debug logging for the integration -

```
logger:
  default: info
  logs:
    custom_components.smartcar: debug
```
deleted and then re-add the integration. post the logs here, (please redact VIN and any other ID's that show)

thanks
